"""Kozmetik etiketleri için ayrı içerik kataloğu."""

COSMETIC_INGREDIENTS = {
    "formaldehyde releaser": {
        "domain": "cosmetic",
        "risk": "high",
        "name": "Formaldehit / formaldehit salıcı",
        "purpose": "Bazı ürünlerde koruyucu sistemin parçası olabilir.",
        "effect": "Hassas kişilerde temas alerjisi ve tahriş riski oluşturabilir.",
    },
    "methylisothiazolinone": {
        "domain": "cosmetic",
        "risk": "high",
        "name": "Methylisothiazolinone",
        "purpose": "Koruyucu olarak kullanılır.",
        "effect": "Alerjik temas dermatiti açısından dikkat gerektirir.",
    },
    "hydroquinone": {
        "domain": "cosmetic",
        "risk": "high",
        "name": "Hydroquinone / Hidrokinon",
        "purpose": "Cilt tonu açıcı ürünlerde kullanılabilir.",
        "effect": "Kullanım alanı ve konsantrasyona göre uzman değerlendirmesi gerektirebilir.",
    },
    "triclosan": {
        "domain": "cosmetic",
        "risk": "high",
        "name": "Triclosan",
        "purpose": "Antibakteriyel etki için kullanılabilir.",
        "effect": "Ürün türü, kullanım alanı ve mevzuat sınırlarıyla birlikte değerlendirilmelidir.",
    },
    "sodium lauryl sulfate": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "SLS",
        "purpose": "Temizleyici ve köpürtücü olarak kullanılır.",
        "effect": "Hassas ciltlerde kuruluk veya tahrişe neden olabilir.",
    },
    "sodium laureth sulfate": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "SLES",
        "purpose": "Temizleyici ve köpük artırıcı olarak kullanılır.",
        "effect": "Hassas ciltlerde kuruluk veya tahrişe neden olabilir.",
    },
    "fragrance": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "Fragrance / Parfüm",
        "purpose": "Ürüne koku vermek için kullanılır.",
        "effect": "Koku alerjisi olan veya hassas ciltli kişilerde reaksiyon oluşturabilir.",
    },
    "phenoxyethanol": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "Phenoxyethanol",
        "purpose": "Koruyucu olarak kullanılır.",
        "effect": "İzin verilen konsantrasyon ve ürün kullanım şekliyle birlikte değerlendirilmelidir.",
    },
    "paraben": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "Paraben",
        "purpose": "Koruyucu olarak kullanılır.",
        "effect": "Paraben türü, izin verilen konsantrasyon ve kişisel hassasiyetle birlikte değerlendirilmelidir.",
    },
    "alcohol": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "Alkol",
        "purpose": "Çözücü veya taşıyıcı olarak kullanılabilir.",
        "effect": "Hassas veya kuru ciltlerde kuruluk ve tahrişe neden olabilir.",
    },
    "mineral oil": {
        "domain": "cosmetic",
        "risk": "medium",
        "name": "Mineral yağ / Paraffinum Liquidum",
        "purpose": "Nem tutucu ve yumuşatıcı olarak kullanılır.",
        "effect": "Genellikle bariyer etkisi sağlar; ürün tipi ve cilt yapısıyla birlikte değerlendirilir.",
    },
    "dimethicone": {
        "domain": "cosmetic",
        "risk": "low",
        "name": "Dimethicone",
        "purpose": "Ciltte koruyucu film ve pürüzsüzlük sağlar.",
        "effect": "Genellikle iyi tolere edilen bir silikon bileşendir.",
    },
}

COSMETIC_ALIASES = {
    "formaldehit": "formaldehyde releaser",
    "formaldehyde": "formaldehyde releaser",
    "hidrokinon": "hydroquinone",
    "sls": "sodium lauryl sulfate",
    "sles": "sodium laureth sulfate",
    "sodium lauryl sulphate": "sodium lauryl sulfate",
    "sodium laureth sulphate": "sodium laureth sulfate",
    "parfüm": "fragrance",
    "parfum": "fragrance",
    "paraben": "paraben",
    "alkol": "alcohol",
    "alcohol": "alcohol",
    "paraffinum liquidum": "mineral oil",
    "mineral oil": "mineral oil",
    "dimethicone": "dimethicone",
}
